/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTablesRouteImport } from './routes/dashboard.tables'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardMenuRouteImport } from './routes/dashboard.menu'
import { Route as DashboardKitchenRouteImport } from './routes/dashboard.kitchen'
import { Route as MSlugTableIdRouteImport } from './routes/m.$slug.$tableId'
import { Route as MSlugTableIdThanksRouteImport } from './routes/m.$slug.$tableId.thanks'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTablesRoute = DashboardTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenuRoute = DashboardMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKitchenRoute = DashboardKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => DashboardRoute,
} as any)
const MSlugTableIdRoute = MSlugTableIdRouteImport.update({
  id: '/m/$slug/$tableId',
  path: '/m/$slug/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugTableIdThanksRoute = MSlugTableIdThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => MSlugTableIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/dashboard/kitchen': typeof DashboardKitchenRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/m/$slug/$tableId': typeof MSlugTableIdRouteWithChildren
  '/m/$slug/$tableId/thanks': typeof MSlugTableIdThanksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/dashboard/kitchen': typeof DashboardKitchenRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/m/$slug/$tableId': typeof MSlugTableIdRouteWithChildren
  '/m/$slug/$tableId/thanks': typeof MSlugTableIdThanksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/dashboard/kitchen': typeof DashboardKitchenRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/m/$slug/$tableId': typeof MSlugTableIdRouteWithChildren
  '/m/$slug/$tableId/thanks': typeof MSlugTableIdThanksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/login'
    | '/menu'
    | '/onboarding'
    | '/pricing'
    | '/signup'
    | '/dashboard/kitchen'
    | '/dashboard/menu'
    | '/dashboard/settings'
    | '/dashboard/tables'
    | '/dashboard/'
    | '/m/$slug/$tableId'
    | '/m/$slug/$tableId/thanks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/features'
    | '/login'
    | '/menu'
    | '/onboarding'
    | '/pricing'
    | '/signup'
    | '/dashboard/kitchen'
    | '/dashboard/menu'
    | '/dashboard/settings'
    | '/dashboard/tables'
    | '/dashboard'
    | '/m/$slug/$tableId'
    | '/m/$slug/$tableId/thanks'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/login'
    | '/menu'
    | '/onboarding'
    | '/pricing'
    | '/signup'
    | '/dashboard/kitchen'
    | '/dashboard/menu'
    | '/dashboard/settings'
    | '/dashboard/tables'
    | '/dashboard/'
    | '/m/$slug/$tableId'
    | '/m/$slug/$tableId/thanks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  MSlugTableIdRoute: typeof MSlugTableIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tables': {
      id: '/dashboard/tables'
      path: '/tables'
      fullPath: '/dashboard/tables'
      preLoaderRoute: typeof DashboardTablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/menu': {
      id: '/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof DashboardMenuRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kitchen': {
      id: '/dashboard/kitchen'
      path: '/kitchen'
      fullPath: '/dashboard/kitchen'
      preLoaderRoute: typeof DashboardKitchenRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/m/$slug/$tableId': {
      id: '/m/$slug/$tableId'
      path: '/m/$slug/$tableId'
      fullPath: '/m/$slug/$tableId'
      preLoaderRoute: typeof MSlugTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug/$tableId/thanks': {
      id: '/m/$slug/$tableId/thanks'
      path: '/thanks'
      fullPath: '/m/$slug/$tableId/thanks'
      preLoaderRoute: typeof MSlugTableIdThanksRouteImport
      parentRoute: typeof MSlugTableIdRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardKitchenRoute: typeof DashboardKitchenRoute
  DashboardMenuRoute: typeof DashboardMenuRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTablesRoute: typeof DashboardTablesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardKitchenRoute: DashboardKitchenRoute,
  DashboardMenuRoute: DashboardMenuRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTablesRoute: DashboardTablesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MSlugTableIdRouteChildren {
  MSlugTableIdThanksRoute: typeof MSlugTableIdThanksRoute
}

const MSlugTableIdRouteChildren: MSlugTableIdRouteChildren = {
  MSlugTableIdThanksRoute: MSlugTableIdThanksRoute,
}

const MSlugTableIdRouteWithChildren = MSlugTableIdRoute._addFileChildren(
  MSlugTableIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  MSlugTableIdRoute: MSlugTableIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
